spring:
  application:
    name: IM-platform

  datasource:
    url: jdbc:mysql://你的IP地址:3306/MyForum?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: 你的用户名
    password: "你的密码"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  rabbitmq:
    host: 你的IP地址
    port: 5672
    username: 你的用户名
    password: "你的密码"
    virtual-host: /MyForum
    publisher-confirm-type: correlated
    publisher-returns: true
    code:
      main-exchanger: main
      server-id: "serverId:"
      message-type: "messageType:"
      private-message: "privateMessage"
      system-message: "systemMessage"

  data:
    redis:
      host: 你的IP地址
      port: 6379
      password: "你的密码"

      lettuce:
        pool:
          max-active: 30
          max-idle: 20
          min-idle: 10
          max-wait: 3000

      code:
        lock: "lock"
        chat-key_to-chat-id: "chatKey:ChatId"
        expire-time: 60
        waiting-time: 30
        online-user-terminal-key: "onlineUserTerminal"