spring:
  application:
    name: IM-platform

  config:
    import: classpath:application-common-git.yaml

  rabbitmq:
    code:
      server-id: "serverId:"
      message-type: "messageType:"
      private-message: "privateMessage"
      system-message: "systemMessage"

  data:
    redis:
      code:
        lock: "lock"
        chat-key_to-chat-id: "chatKey:ChatId"
        expire-time: 60
        waiting-time: 30
        online-user-terminal-key: "onlineUserTerminal"

logging:
  level:
    root: info